// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workforce-dashboard/Cockpit.tsx": () => import("../components/mockups/workforce-dashboard/Cockpit.tsx"),
  "./components/mockups/workforce-dashboard/Queue.tsx": () => import("../components/mockups/workforce-dashboard/Queue.tsx"),
  "./components/mockups/workforce-dashboard/Scorecard.tsx": () => import("../components/mockups/workforce-dashboard/Scorecard.tsx")
};
